### ISSUE TITLE
Improve tabs in Browse Our Top Niche section

### ISSUE THREAD

**Issue by masterHAWK99** [Bartek-Figat/---BBARDS---#67]
Please fix tabs in **Browse Our Top Niche** section to match the look with design.

Currently:
![image](https://user-images.githubusercontent.com/60447475/198075875-cad5e77f-9776-4518-95c7-3ddd50b4759a.png)

Design:
![image](https://user-images.githubusercontent.com/60447475/198076633-5c19cd5c-e995-4faf-8442-9a670c1c42c3.png)

**Comment by najeebkp** [comment]
Hi @masterHAWK99 please assign this to me
