### ISSUE TITLE
Improve responsiveness in the section "Find your needs in our best Featured Ads"

### ISSUE THREAD

**Issue by Bartek-Figat** [Bartek-Figat/---BBARDS---#71]
**Please fix the responsiveness**
---**lg-screen**---
--**_current_**--
![responsiveness-lg](https://user-images.githubusercontent.com/67811830/198149866-4acb006b-01cf-4fa6-8dec-9fa73862381b.png)
--**_desing_**--
![responsiveness-lg-orginal](https://user-images.githubusercontent.com/67811830/198149899-a838adfe-aaaa-4efa-b019-fd3f1b6e2bdb.png)
---**md-screen**---
--**_current_**--
![responsiveness-md](https://user-images.githubusercontent.com/67811830/198150245-6f042682-c558-4526-add7-9088c88daf52.png)
--**_desing_**--
![responsiveness-md-orginal](https://user-images.githubusercontent.com/67811830/198150268-8dc9bc05-34e6-4aab-a410-95b41b573c76.png)
---**sm-screen**---
--**_current_**--
![responsiveness-sm](https://user-images.githubusercontent.com/67811830/198150557-791e48ff-f74a-47e2-b383-f7342ba5ce98.png)
--**_desing_**--
![responsiveness-sm-orginal](https://user-images.githubusercontent.com/67811830/198150580-ec42f61b-50ec-40c7-92e0-32955c3848a0.png)

**Comment by srijoy-paul** [comment]
Hey @Bartek-Figat Can you assign me this task?

**Comment by Bartek-Figat** [comment]
You got it @srijoy-paul 😊
